spring:
  application:
    name: mysql-primary-key-test

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:mysql:8.0.32:///test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        highlight_sql: false

---
spring:
  config:
    activate:
      on-profile: silence
  main:
    banner-mode: OFF
  datasource:
    url: jdbc:tc:mysql:8.0.32:///test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        highlight_sql: false
    hibernate:
      ddl-auto: create

log4j:
  configurationFile: classpath:log4j2-silence.yml
